{% set name = "axe-selenium-python" %}
{% set version = "2.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/axe-selenium-python-{{ version }}.tar.gz
  sha256: 9203ff59c79edcfbcbd676ae55ca35f257e9afb663adbcbc210e3b0d802255ae

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pytest >=3.0
    - python >={{ python_min }}
    - selenium >=3.0.2

test:
  imports:
    - axe_selenium_python
    - axe_selenium_python.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/mozilla-services/axe-selenium-python
  summary: Python library to integrate axe and selenium for web accessibility testing.
  license: MPL-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
